# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:51
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0003_auto_20160409_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='guideId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='travelerId',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='activeRoutes',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='pendingRoutes',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='activeRoutes',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='bookmarks',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='pendingRoutes',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
