# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('guide', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rut', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999L)])),
                ('dateOfBirth', models.DateField()),
                ('mail', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999999999999L)])),
                ('languages', jsonfield.fields.JSONField()),
                ('guideId', models.IntegerField()),
                ('travelerId', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(max_length=500)),
                ('pendingRoutes', jsonfield.fields.JSONField()),
                ('activeRoutes', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('description', models.CharField(max_length=500)),
                ('pointsOfInterest', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(max_length=500)),
                ('foodConsiderations', models.CharField(max_length=500)),
                ('bookmarks', jsonfield.fields.JSONField()),
                ('pendingRoutes', jsonfield.fields.JSONField()),
                ('activeRoutes', jsonfield.fields.JSONField()),
            ],
        ),
    ]
