# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concreteroute',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rut',
        ),
        migrations.AddField(
            model_name='concreteroute',
            name='guideId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Routes.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concreteroute',
            name='routeId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Routes.Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Routes.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Routes.CustomUser'),
            preserve_default=False,
        ),
    ]
