# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0002_auto_20160409_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='guideId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='travelerId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='activeRoutes',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='pendingRoutes',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='activeRoutes',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='bookmarks',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='pendingRoutes',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
