# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 04:17
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0005_auto_20160409_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isGuide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isTraveler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medicalConditions',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.DurationField(default=datetime.datetime(2016, 4, 10, 4, 17, 25, 179908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='foodConsiderations',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
