# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0006_auto_20160410_0117'),
        ('Routes', '0006_auto_20160410_0439'),
    ]

    operations = [
    ]
